package com.chihuo.bussiness;

import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

// Generated 2012-10-5 16:47:30 by Hibernate Tools 3.4.0.CR1

/**
 * Desk generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.NONE)
public class Desk implements java.io.Serializable {
	
	private int id;
	private String name;
	private Integer capacity;
	
	private Integer status;
	private Restaurant restaurant;
	private DeskType deskType;
	private Set<Order>orderList;
	
	public Desk() {
	}

	public Desk(int id) {
		this.id = id;
	}

	public Desk(int id, DeskType deskType, String name, Integer capacity) {
		this.id = id;
		this.deskType = deskType;
		this.name = name;
		this.capacity = capacity;
	}

	@XmlElement
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public DeskType getDeskType() {
		return this.deskType;
	}

	public void setDeskType(DeskType deskType) {
		this.deskType = deskType;
	}

	@XmlElement
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@XmlElement
	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Restaurant getRestaurant() {
		return restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}
	
	
	@XmlElement
	public Integer getTid(){
		if (this.deskType != null) {
			return this.deskType.getId();
		}
		return null;
	}

	public Set<Order> getOrderList() {
		return orderList;
	}

	public void setOrderList(Set<Order> orderList) {
		this.orderList = orderList;
	}

}
