package com.chihuo.bussiness;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

// Generated 2012-11-27 16:53:06 by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Device implements java.io.Serializable {

	private Integer id;
	private String deviceid;
	private Integer ptype;
	private Date registerTime;
	

	public Device() {
	}


	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public String getDeviceid() {
		return deviceid;
	}


	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}


	public Integer getPtype() {
		return ptype;
	}


	public void setPtype(Integer ptype) {
		this.ptype = ptype;
	}


	public Date getRegisterTime() {
		return registerTime;
	}


	public void setRegisterTime(Date registertime) {
		this.registerTime = registertime;
	}
}
