package com.chihuo.bussiness;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.chihuo.util.JaxbDateSerializer;

// Generated 2012-11-27 16:53:06 by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Favorite implements java.io.Serializable {

	private Integer id;
	@XmlJavaTypeAdapter(JaxbDateSerializer.class)
	private Date time;
	
	@XmlTransient
	private User user;
	@XmlTransient
	private Restaurant restaurant;

	public Favorite() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Restaurant getRestaurant() {
		return restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}
	
	@XmlElement
	public Integer getRid(){
		if(restaurant != null){
			return restaurant.getId();
		}
		return null;
	}
	
	@XmlElement
	public String getRestaurantName(){
		if(restaurant != null){
			return restaurant.getName();
		}
		return null;
	}
}
