package com.chihuo.bussiness;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

// Generated 2012-10-7 10:39:14 by Hibernate Tools 3.4.0.CR1

/**
 * Recipe generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(propOrder={"id","name","price","description","image","pinyin","cid"})
public class Recipe implements java.io.Serializable {
	
	private Integer id;
	private String name;
	private String description;
	private String image;
	private Double price;
	private String pinyin;
	
	private Integer status;
	private Restaurant restaurant;
	private Category category;

	public Recipe() {
	}

	public Recipe(Restaurant restaurant, Category category, String name,
			String description, String image) {
		this.restaurant = restaurant;
		this.category = category;
		this.name = name;
		this.description = description;
		this.image = image;
	}
	
	@XmlElement
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@XmlElement
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@XmlElement
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@XmlElement
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	
	@XmlElement
	public Integer getCid(){
		if (this.category != null) {
			return this.category.getId();
		}
		return null;
	}

	@XmlElement
	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@XmlElement
	public String getPinyin() {
		return pinyin;
	}

	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}

}
